apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: fullstack-app
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort

