# database/mongo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: fullstack-app
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4= # base64 encoded 'admin'
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ= # base64 encoded 'password'

